objects/BCTAC__c.object
<CustomObject><fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Community_Content_Status__c</fullName>
        <label>Community Content Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Publish_Date__c</fullName>
        <label>Publish Date</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Babson Connector Terms &amp; Conditions (BCTAC)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>BCTAC</label><nameField>
        <displayFormat>BCTAC -{00000000}</displayFormat>
        <label>BCTAC Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>BCTAC</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/BabsonTMControllerTest.cls
@isTest
public class BabsonTMControllerTest{
     @isTest static void test_validate() {
         
         
         BCTAC__c oBCTAC =  new BCTAC__c();
         oBCTAC.Community_Content_Status__c = 'Approved';
         oBCTAC.Title__c = 'tret';
         oBCTAC.body__c = 'trre';
         oBCTAC.Publish_Date__c = system.now();
         insert oBCTAC;
         
         BabsonTMController oBabsonTMController = new  BabsonTMController();
     
     }


}