objects/BCTAC__c.object
<CustomObject><fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields><fields>
        <fullName>Community_Content_Status__c</fullName>
        <label>Community Content Status</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Publish_Date__c</fullName>
        <label>Publish Date</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Babson Connector Terms &amp; Conditions (BCTAC)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>BCTAC</label><nameField>
        <displayFormat>BCTAC -{00000000}</displayFormat>
        <label>BCTAC Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>BCTAC</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/BabsonTMController.cls
public class BabsonTMController{
    public string body{get;set;}
    public string title{get;set;}
    list<BCTAC__c>  lstVTAC ;
    
    public BabsonTMController(){
        lstVTAC = new list<BCTAC__c>();
        lstVTAC  = [SELECT Body__c,Community_Content_Status__c,End_Date__c,Publish_Date__c,Title__c FROM BCTAC__c WHERE
                    Community_Content_Status__c =:'Approved' order by Publish_Date__c desc LIMIT 1];
                    
        if(lstVTAC.size()>0 && lstVTAC !=null){
            body =lstVTAC[0].body__c;  
            title =  lstVTAC[0].Title__c ;   
        }
    
    
    }





}