objects/User.object
<CustomObject><fields>
        <fullName>User_Login_Count__c</fullName>
        <label>User Login Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

objects/User_Login_History__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>This object will store the user logged in history.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>User Login History</label><nameField>
        <label>User Id</label>
        <type>Text</type>
    </nameField><pluralLabel>User Login Histories</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

classes/batchUserLoginCount.cls
global class batchUserLoginCount implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,Name FROM User_Login_History__c';
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<User_Login_History__c> scope) {
        map<string,integer>  mapCount = new map<string,integer> ();
        for(User_Login_History__c oUH : scope){
            if(mapCount.containsKey(oUH.Name)){
                mapCount.put(oUH.name,mapCount.get(oUH.Name)+1);
            }else{
                mapCount.put(oUH.name,1);
            }
        }
        
        System.debug('mapCount ==>>>'+mapCount);
        List<User>  lst1 = new List<User>();
        for(String str : mapCount.keySet()){
            User u = new user(id= str);
            u.User_Login_Count__c = mapCount.get(str);
            lst1.add(u);
        
        }
        
        if(lst1.size()>0){
           update lst1; 
            
        }
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
}